[build]
  # Build command for Vite
  command = "npm run build"
  # Directory to publish
  publish = "dist"

# SPA redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Set custom headers for better performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
